### ISSUE TITLE
How to create StaticMesh in console application?

### ISSUE THREAD

**Issue by oschakravarthi** [Harrison1/unrealcpp#1]
Hi, thanks for this code.
I am trying to develop a console application which  generates few meshes and save them as .uasset files and pack them as .Pak files. 

I am trying to modify the BlankApplication (which comes as part of UE4 guthub source) to achieve the functionality. I could not understand what modules to include (the build targets stuff etc.)

Can you please give some clues?

Thanks in advance.

**Comment by Harrison1** [comment]
hey @oschakravarthi , thanks for reaching out, my fault for the super late reply.

I'm not sure how to tackle issue, this seems a like difficult task to accomplish. However, If I think of anything or if I come across any code that might help I'll definitely let you know. So unfortunately at the moment I am unsure how to go about solving this problem.

Best of luck.

**Comment by vinayakap** [comment]
I know it's late to comment, if somebody is still looking for issue, following insight might help.

For generating meshes, see [ProceduralMeshComponent ](https://docs.unrealengine.com/en-US/API/Plugins/ProceduralMeshComponent/UProceduralMeshComponent/index.html). I think you need to supply geometric information like, vertices, triangles, normals, tangents for automated task. 

I don't know how to save generated mesh as .uasset, but it's possible with engine's editor module.
